### ISSUE TITLE
README: Confusing note about version 2.0.0

### ISSUE THREAD

**Issue by fyockm** [nlf/precommit-hook#47]
Perhaps I was just being dense, but I found this line from the README confusing.

> As of version 2.0.0 of this module, the configuration key in package.json has been changed to "pre-commit" with a dash, instead of the old "precommit". All other functionality should work the same.

I realize now that that version 2.0.0 is forthcoming, but the currently published version in npm is `1.0.7`. Took me a bit to figure out that I should still use 'the old "precommit"' rather than 'pre-commit' for config in my `package.json`.

Might I recommend removing that line until version 2.0.0 is actually released?

**Comment by Trott** [comment]
Another possibility is to change it to more clearly be a statement about the future rather than the present. Something like:

> In the upcoming version 2.0.0 of this module, the configuration key in package.json will be changed to "pre-commit" with a dash, instead of the old "precommit".

If it's already true in the repo but not in the released version:

> In the upcoming version 2.0.0 of this module (and the current master branch in this repository), the configuration key in package.json will be changed to "pre-commit" with a dash, instead of the old "precommit".

**Comment by nlf** [comment]
Clarified. Sorry for the confusion!

**Comment by omichelsen** [comment]
Hey great project, just what I needed. Any news on releasing 2.0.0? This tripped me up as well, but found this issue before creating a new one :)

**Comment by nlf** [comment]
Just released it today actually :)

**Comment by fyockm** [comment]
:+1:
