### ISSUE TITLE
automatically add `.validate.json` to `.gitignore`?

### ISSUE THREAD

**Issue by fyockm** [nlf/precommit-hook#48]
I know you don't touch `.gitignore` right now, but I think it might make sense to automatically add `.validate.json` to that file?

**Comment by nlf** [comment]
I'm not sure on this one.

I can see where it would make sense to add it to `.gitignore`, but I can also see where it would be nice to know if it changes and has an impact on the outcome of your testing, which would be provided by git if it were a tracked file.

I'm going to hold off on making this change until we get some more opinions voiced.

**Comment by fyockm** [comment]
Perhaps incorrectly, I was basing this issue upon this from the README: "If you need to make changes to the hook's configuration, you should always make them in your `package.json` as the `.validate.json` file will be overwritten every time the install script is run."

**Comment by nlf** [comment]
Right. The `.validate.json` file contains the defaults that are provided by the author of your pre-commit hook (in the case of this project, that's me). The idea is that you can make whatever tweaks you want in your own `package.json`, and whatever the hook can't configure via `package.json` it reads `.validate.json` to lookup.

**Comment by nlf** [comment]
yeah, i think i've decided against this. the file should be committed to ensure transparency when it changes for whatever reason (especially between users)

**Comment by fyockm** [comment]
Fair enough. Thanks for considering.
