### ISSUE TITLE
2.0.0 broken

### ISSUE THREAD

**Issue by omichelsen** [nlf/precommit-hook#49]
After the update my config (which I just set up successfully yesterday) has broken.

My `package.json` looks like this:

```
{
    "scripts": {
      "lint": "jshint Gruntfile.js server.js app/ config/"
    },
    "pre-commit": ["lint"]
}
```

But the generated `.validate.json` looks like this:

```
{
  "scripts": {
    "lint": "jshint ."
  },
  "pre-commit": ["lint", "validate", "test"]
}
```

Furthermore there is no way to stay on version 1.0.7, since you basically added the core dependency as `*`. This is pretty bad versioning. 

Hope you will be able to fix it, because this means I have to remove your package and/or find another way to setup my pre-commits :-1:

**Comment by nlf** [comment]
I don't follow, how is this broken? The .validate.json file only provides defaults, your package.json should override them without issue. Is this not the case?

**Comment by omichelsen** [comment]
No, I tried making an empty project, added the pre-commit config to `package.json` and ran `npm install precommit-hook`.

It generated the `.validate.json` that you see above.

**Comment by nlf** [comment]
This is expected. The `.validate.json` file isn't generated based on your `package.json`, it is a static file provided by the `precommit-hook` package. It provides a way of configuring default behavior for the hook without having to modify your project's existing files.

The configuration within that file is defaults only, and if you have configuration in your `package.json` (which you do) that will be used instead. In your case `.validate.json` simply becomes an extra file, which you can delete if you would prefer.

You're right, though, that the version for `git-validate` in the package.json should not have been `*`, that slipped through when I was testing and will be fixed.

**Comment by omichelsen** [comment]
In that case I don't understand the wording in your readme:

> A `.validate.json` file will also be created and leveraged by `git-validate` in order to run your scripts.

That sounds to me like it will be generated and used for running the scripts?

**Comment by nlf** [comment]
You're right, that's misleading. I'll clarify the documentation.

**Comment by nlf** [comment]
Does this make more sense?

> A .validate.json file will also be created to provide defaults to git-validate in order to run your scripts. This configuration is only used if you have not specified your own configuration in package.json.

**Comment by omichelsen** [comment]
Much clearer :+1:

**Comment by nlf** [comment]
Closed via 25f124068c411c530b1861e6c1521d0c4febf05d

**Comment by omichelsen** [comment]
I experienced a lot of errors running my pre-commit hook after the update, but I guess that must've been something else. I can't recreate that in my test project.

Thanks :)

**Comment by nlf** [comment]
Happy to help, feel free to open new issues if you run across anything you can reproduce :)
