### ISSUE TITLE
hooks per branch

### ISSUE THREAD

**Issue by fyockm** [nlf/precommit-hook#51]
Not sure if it could work this way, but it would be nice if I could specify a branch as a target for running the hooks. For example, I only want to run my tests in the `master` branch. I know other branches will break tests, but I still want to be able to make commits- in an effort to share code. Is there some way to accomplish this?

**Comment by Trott** [comment]
You could bypass the pre-commit hook with `git commit --no-verify`. That might not be as convenient as having it baked into precommit-hook itself, but just FYI if you need/want the functionality right now.

**Comment by nlf** [comment]
That's an interesting idea.. I'll have to think about how to implement that.

**Comment by fyockm** [comment]
@Trott thanks for the suggestion. that should work for now.
@nlf not sure if this helps: http://stackoverflow.com/questions/6372334/git-commit-hooks-per-branch

cc/ @sabymike

**Comment by nlf** [comment]
so I'm trying to figure out the best way to implement this without breaking everything, and my thought is this.. what if the current behavior remains as-is, in that setting `pre-commit` applies that list of hooks to all branches, but if you have a key `pre-commit-somebranch` then that array only applies to the branch `somebranch`.

For example:

```js
{
  "pre-commit": ["lint", "test"],
  "pre-commit-dev": ["lint"]
}
```

in this instance if you're in the branch `dev` only the `lint` script will be run, every other branch both `lint` and `test` will be run.

thoughts?

**Comment by nlf** [comment]
was easy enough, so i went ahead and did it.

closed via https://github.com/nlf/git-validate/issues/25

**Comment by fyockm** [comment]
@nlf Thanks for implementing!

It's backwards from how I was thinking about it, but should get the job done. I only want tests to run in the master branch, so this should work:
```
    "pre-commit": ["lint"],
    "pre-commit#master": ["lint", "test"],
```
