### ISSUE TITLE
Allow selection of what program defaults to install (if any)

### ISSUE THREAD

**Issue by pgilad** [nlf/precommit-hook#53]
For example, in my project I may only use eslint, or jscs or some other alternative and don't want a .jshintrc and .jshintignore file spammed

**Comment by nlf** [comment]
This is the reason [git-validate](https://github.com/nlf/git-validate) exists. This module is a simple wrapper around `git-validate`.

It would be trivial to fork this repo, change its dependencies and configuration files, and publish a new module and use that instead.

You don't even need to worry about keeping track of the upstream.

**Comment by pgilad** [comment]
:clap: thanks!
