### ISSUE TITLE
.validate.json resets each time `npm install` is run

### ISSUE THREAD

**Issue by diasdavid** [nlf/precommit-hook#55]
Hi @nlf , I noticed that if I remove the node_modules folder and `npm i` all of the dependencies again, precommit-hook resets the .validate.json to default, losing the previous configuration.

**Comment by nlf** [comment]
this isn't really documented well here, but this behavior is intentional. configuration should be done in your package.json, which supports all the same keys as `.validate.json`. the `.validate.json` is the file that contains this packages defaults and will always be overwritten on reinstall.

**Comment by diasdavid** [comment]
Interesting. Why not those keys to the package.json during npm install if they are not there yet?

**Comment by nlf** [comment]
because i don't want to modify existing files that aren't my own :)
