### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by mabasic** [nlf/precommit-hook#58]
When I run `npm run-script lint` I get:

```
λ npm run-script lint

> @ lint C:\Repositories\chrome-wakatime
> jsxhint --jsx-only .
```

But when I do a commit I get:

```
λ git cm -m "Updated tests."
find: ./node_modules/.bin/jest: No such file or directory
find: ./node_modules/.bin/jsx: No such file or directory
running lint...passed!
```

This is my package.json file:

```
"scripts": {
    "lint": "jsxhint --jsx-only ."
  },
  "pre-commit": ["lint"],
```

Why am I getting:

```
find: ./node_modules/.bin/jest: No such file or directory
find: ./node_modules/.bin/jsx: No such file or directory
```

?

**Comment by mabasic** [comment]
Ok, those were some broken links in `node_modules/.bin/` directory. But still why were they triggered?

**Comment by nlf** [comment]
this is because the validate.sh script in git-validate runs gnu find, which is apparently triggering an error with invalid symlinks. it's cosmetic for right now, but i'll work on fixing it.

**Comment by mabasic** [comment]
It's not a real issue, I was just curious about how it works. Thank you for explaining.

btw This package is really good :)
