### ISSUE TITLE
find: invalid predicate `-iwholename'

### ISSUE THREAD

**Issue by mabasic** [nlf/precommit-hook#60]
I'm implementing this on another project and when I run `jshint .` everything works, but when i run `git commit` I get this message:

```
find: invalid predicate `-iwholename'
```

Do you know what does it mean or have an idea where to start looking? I can't find anything on google.

This is my package.json:

```
  "scripts": {
    "lint": "jshint ."
  },
  "pre-commit": [
    "lint"
  ],
```

**Comment by nlf** [comment]
What operating system are you on?

**Comment by mabasic** [comment]
I am on Windows. That has occurred to me also and when I run the command `git commit` from linux VM it works normal. But I have another project on windows and when I run `git commit` it works normal.

**Comment by nlf** [comment]
I made a change to the git-validate script to use the -iwholename predicate. How did you get your unix tools in windows? Through the git installer? Cygwin?

**Comment by mabasic** [comment]
I am using [Cmder](http://gooseberrycreative.com/cmder/), let me just update it to the latest version

**Comment by mabasic** [comment]
Still the same issue.

**Comment by mabasic** [comment]
mysygit 1.9.5

**Comment by nlf** [comment]
I'll get this fixed up, I got a virtual machine running where I can reproduce this. I'll close this issue when I push a patch

**Comment by mabasic** [comment]
Ok, nice. Thank you very much

**Comment by nlf** [comment]
Ok, I think I got it. Reinstall to pull in the new git-validate and let me know if that took care of the problem.

**Comment by mabasic** [comment]
It's working now, thank you.
