### ISSUE TITLE
jshint could be optional

### ISSUE THREAD

**Issue by marapper** [nlf/precommit-hook#63]
It's good module but every time I execute npm install it creates .jshintignore and .jshintrc. It would be better if module suggest it not to force it (for ex. I use eslint).

**Comment by nlf** [comment]
the point of this particular module is to install jshint and some configuration for it, if you don't want those features look at [git-validate](https://github.com/nlf/git-validate) instead

**Comment by marapper** [comment]
so precommit-hook is strange naming.

**Comment by nlf** [comment]
this module was originally a no-frills thing that was written for my team's use. as a result of external users wanting more features and flexibility i broke out the key parts into a separate module [git-validate](https://github.com/nlf/git-validate) and kept this module backwards compatible so it continued to work in a similar way as it always has.

**Comment by umayr** [comment]
@marapper I'm late to the party but I had this very same issue so I created another module using `git-validate` under the hood that supports both jshint and eslint. It asks you after installation what do you want to use. And if you already have either `.jshintrc` and `.eslintrc` in your root directory, it'll skip copying config files and only install pre-commit hooks. You can find it here: https://github.com/umayr/abracadabra.

**Comment by dd1994** [comment]
I find this https://github.com/observing/pre-commit
