### ISSUE TITLE
Do not create .jshint files

### ISSUE THREAD

**Issue by nkbt** [nlf/precommit-hook#64]
Lots of projects now use ESlint and creating JSHint configs automatically on installing precommit-hook package is strange. Maybe it is better to create an empty "lint" npm script instead and leave the linter choice and configuration up to developer?

**Comment by nlf** [comment]
Use [git-validate](https://github.com/nlf/git-validate) directly or fork this repo and use it as a template to provide your own linter and configuration

**Comment by nkbt** [comment]
Thanks

**Comment by Stupidism** [comment]
https://www.npmjs.com/package/precommit-hook-eslint
