### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by luisrudge** [nlf/precommit-hook#67]
I added some lint errors, but it's still making the commit
```js
{
  "pre-commit": ["lint"],
  "scripts": {
    "lint": "eslint ./app/**/*.js"
  }
}
```

```
λ git commit -m "test"
env: git: No such file or directory
this does not look like a git repository.. exiting
[dev 2c6a426] test
warning: LF will be replaced by CRLF in code/.jshintignore.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in code/.jshintrc.
The file will have its original line endings in your working directory.
 3 files changed, 13 insertions(+)
 create mode 100644 code/.jshintignore
 create mode 100644 code/.jshintrc
```

**Comment by dibikhin** [comment]
Same picture on Windows 8. Git is ok, everything is committed. On Xubuntu works well.
    >git commit -am "test 6"
    env: git: No such file or directory
    this does not look like a git repository.. exiting
    [some-branch c25d4f7] test 6
    1 file changed, 1 insertion(+)

**Comment by nlf** [comment]
interesting.. seems like both of you are on windows, i'll have to do a little more testing.

how do you have git installed?

**Comment by luisrudge** [comment]
I use Chocolatey: `choco install git.install` (https://chocolatey.org/packages/git.install)

**Comment by dibikhin** [comment]
I use latest stable version from git-scm.com

**Comment by nlf** [comment]
and are you both running `git commit` from a command line of some sort? git bash or the windows command prompt or powershell or something? or from a gui?

**Comment by dibikhin** [comment]
I've used 'cmd' and Git Bash both with 'run as administrator' for 'git commit'.

**Comment by dibikhin** [comment]
When I run in Git Bush (as administrator) 'env -i git rev-parse --show-toplevel' it gives me 'env: git: No such file or directory'. I've installed Git with 'Use Git and optional Unix tools from the Windows Command Prompt' checked.

**Comment by dibikhin** [comment]
I've removed all 'env -i' from my '.git\hooks\precommit' file locally and it helped.
Now pre-commit hook run my scripts.
Also I've changed my package.json (note './')
"scripts": {
    "just-test": "./just.bat"
},
"pre-commit": [
    "just-test"
]

**Comment by noelmace** [comment]
:+1: - I'm also on Windows 8 x64
FYI :
node : v5.4.0 via msi x64
git : v2.6.2 via Cygwin
and I'm using cygwin via cmder

**Comment by noelmace** [comment]
FYI : this is currently my patch (#69 included)

```
/* some dependencies' patches */

var fs = require('fs')

////////////// precommit-hook ////////////////

// see https://github.com/nlf/precommit-hook/issues/69 and https://github.com/nlf/precommit-hook/issues/67

if (process.platform === 'win32') {
    fs.readFile('.git/hooks/pre-commit', 'utf8', function (err,data) {
      if (err) {
        return console.log(err);
      }
      var result = data.replace(/env -i git/g, 'git');

      fs.writeFile('.git/hooks/pre-commit', result, 'utf8', function (err) {
         if (err) return console.log(err);
      });
    });
}

var nodeConf = require('./package.json');

if(typeof nodeConf['jshint'] === 'undefined'){
    fs.unlink('.jshintrc', function(err, data) {
        if (err) {
            return err.code !== 'ENOENT' && console.log(err);
        }
        return console.log('.jshintrc removed');
    });

    fs.unlink('.jshintignore', function(err, data) {
        if (err) {
            return err.code !== 'ENOENT' && console.log(err);
        }
        return console.log('.jshintignore removed');
    });
}
```
