### ISSUE TITLE
Ignore "projects" in repository

### ISSUE THREAD

**Issue by happypoulp** [nlf/precommit-hook#70]
Hi,

First of all thanks for this module, its usage is simple and yet very powerful!

I came across what I thought that was an issue but after looking at your code, it seems more like it's a feature that incidentally triggers an issue for us. So the present issue is more a feature request than a real issue.

Your way of finding all projects in the current repo to check all of them, is assuming that all package.json are actually intended to be used for a check. In our repository, we have a build process that copies our main package.json to another directory (still inside the same repository) to prepare a complete folder ready for production. Incidentally, this copy of our package.json is detected by pre-commit hook and all hooks are run from that build folder. This issue is that this build folder is missing lots of packages that were intentionally not installed for production - like babel-node - which then triggers some failure in precommit hooks.

I found a workaround by editing the package.json's copy to make sure that it won't be detected by pre-commit hooks but I would find it much better to be able to somehow ignore some folders from being scanned to find a package.json.

Would you think this is a valid feature request or would you say that the current "patch package.json" strategy is better?

Thanks.

**Comment by nlf** [comment]
the more i think about it the more i think patching your package.json is the way to go.. implementing this as a feature in git-validate could end up pretty complicated

**Comment by happypoulp** [comment]
Ok, fair enough, the patch solution is working so I'll keep it then. Thanks!
