### ISSUE TITLE
behavior of 'npm ls`

### ISSUE THREAD

**Issue by missinglink** [nlf/precommit-hook#73]
heya, more of a question than a bug report..

I have been getting infuriated with the `validate` step recently as it always seems to complain about my modules, after looking over the code it seems the culprit is `npm ls`.

Now, this may only affect certain versions of node, I didn't have these issues in the past but at some point `npm` switched from nesting `node_modules` dirs to putting them all in one dir.

so when I run `git commit` it runs `npm ls` and then my commit fails, basically this:

```
$ rm -rf node_modules
$ npm cache clean
$ npm i
$ npm ls
... bunch of stuff followed by

├─┬ iso3166-1@0.2.8
│ └─┬ zlib-browserify@0.0.3
│   └── UNMET DEPENDENCY tape@~0.2.2

...

    │ ├── right-align@0.1.3
    │ └── wordwrap@0.0.2
    ├── decamelize@1.2.0
    └── window-size@0.1.0

npm ERR! missing: tape@~0.2.2, required by zlib-browserify@0.0.3

$ echo $?
1
```

surely I'm not the only one having this issue? how are you working around this?

```
$ node --version
v6.3.0

$ npm --version
3.10.3
```

**Comment by missinglink** [comment]
ok, so this is an issue with `npm@3+`, if I do the following `sudo npm i -g npm@2.15.8` then `npm ls` works as expected and responds `exit 0`

**Comment by nlf** [comment]
interesting, you should open an issue on npm and see if they can figure out why it fails in npm@3

**Comment by missinglink** [comment]
https://github.com/npm/npm/issues/13352

**Comment by Trott** [comment]
Bug does not seem to exist running with recent/current npm, but if I'm wrong about that, please comment or (if GitHub lets you) re-open the issue. Thanks!
