### ISSUE TITLE
ESLint by default?

### ISSUE THREAD

**Issue by Trott** [nlf/precommit-hook#78]
Since ESLint is now the _de facto_ standard, would you be open to a PR that would make the default ESLint with the ESLint-recommended defaults? Or would that be a non-starter?

Ref: http://www.npmtrends.com/eslint-vs-jshint-vs-jslint-vs-standard

**Comment by Trott** [comment]
Meh, never mind. I see this is going to be jshint and always jshint. Cool by me.

**Comment by nlf** [comment]
I actually haven’t used this particular module in quite some time, so if updating it to eslint is something people who actually use it are interested in, I’m for it.
